### PR TITLE
Add Simplified Chinese Localization

### PR DESCRIPTION
**Pull request by kiritantakechi**
Please review my code

### CODE REVIEW

**Review by vnepogodin — APPROVED** [review]
LGTM

**Comment by kiritantakechi** [comment]
Can it be merged now?

**Comment by vnepogodin** [comment]
Yeah I just noticed our validation logic is working incorrectly for regional language id.
I'll just merge and fix in next commit

**Comment by vnepogodin** [comment]
Many thanks!

**Comment by kiritantakechi** [comment]
t seems that the representation used by unic_langid is inconsistent with Linux's localization method. While Linux uses "zh_CN" for Simplified Chinese, unic_langid represents it as "zh_Hans".🤔

**Comment by vnepogodin** [comment]
> t seems that the representation used by unic_langid is inconsistent with Linux's localization method. While Linux uses "zh_CN" for Simplified Chinese, unic_langid represents it as "zh_Hans".🤔

I've fixed it here https://github.com/CachyOS/CachyOS-Welcome/commit/96b64da3bfba422ddc40b211b70e66f228b00965

**Pull request merged**
